### PR TITLE
Skip files that are already present. This prevent re-downloads.

### PR DESCRIPTION
**Pull request by svaningelgem**
This should skip already downloaded files. Saves on bandwidth (and time).
Only the last one (in time) will be re-downloaded (it's my expectation that the last one would change the most).

### CODE REVIEW

**Comment by edouardswiac** [comment]
Thanks for your contribution! Please pull the latest master and this should go green ✅

**Comment by svaningelgem** [comment]
It seems you removed dependencies of Python 2.6 & 2.7 from the travis checks?
Anyhow, I also fixed it for backwards compatibility :-)

**Comment by edouardswiac** [comment]
Yes! I have dropped support for python 2. Can you include a quick unit test with your change? see test.py. Thanks!

**Comment by svaningelgem** [comment]
Thanks a lot Edouard!

**Pull request merged**
